export const creatorRewardPoolFactoryAbi = [
  {
    type: "function",
    name: "implementation",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolFeeRecipient",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "defaultProtocolFeeRate",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createCreatorRewardPool",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "name", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
    ],
    outputs: [{ name: "pool", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createCreatorRewardPoolWithCustomFee",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "name", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
      { name: "protocolFeeRate", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "pool", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createCreatorRewardPoolWithoutFee",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "name", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
    ],
    outputs: [{ name: "pool", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "activateCreatorPool",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deactivateCreatorPool",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addUser",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "user", type: "address", internalType: "address" },
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
      { name: "allocation", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateUserAllocation",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "user", type: "address", internalType: "address" },
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
      { name: "newAllocation", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeUser",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "user", type: "address", internalType: "address" },
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "batchAddUsers",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
      { name: "users", type: "address[]", internalType: "address[]" },
      { name: "allocations", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "batchUpdateUserAllocations",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
      { name: "users", type: "address[]", internalType: "address[]" },
      { name: "newAllocations", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "batchRemoveUsers",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
      { name: "users", type: "address[]", internalType: "address[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "grantSignerRole",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "signer", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimRewardFor",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      {
        name: "data",
        type: "tuple",
        internalType: "struct ICreatorRewardPool.ClaimData",
        components: [
          { name: "user", type: "address", internalType: "address" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "tokenAddress", type: "address", internalType: "address" },
          {
            name: "tokenType",
            type: "uint8",
            internalType: "enum ICreatorRewardPool.TokenType",
          },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeSignerRole",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "signer", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getCreatorPoolInfo",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct CreatorRewardPoolFactory.CreatorPoolInfo",
        components: [
          { name: "creator", type: "address", internalType: "address" },
          { name: "pool", type: "address", internalType: "address" },
          { name: "active", type: "bool", internalType: "bool" },
          { name: "name", type: "string", internalType: "string" },
          { name: "description", type: "string", internalType: "string" },
          { name: "protocolFeeRate", type: "uint256", internalType: "uint256" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCreatorPoolAddress",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isCreatorPoolActive",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasCreatorPool",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalCreatorPools",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCreatorAtIndex",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "validateCreatorAllocations",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
    ],
    outputs: [
      { name: "isValid", type: "bool", internalType: "bool" },
      { name: "totalAllocations", type: "uint256", internalType: "uint256" },
      { name: "availableBalance", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "CreatorPoolCreated",
    inputs: [
      { name: "creator", type: "address", indexed: true, internalType: "address" },
      { name: "pool", type: "address", indexed: true, internalType: "address" },
      { name: "name", type: "string", indexed: false, internalType: "string" },
      { name: "description", type: "string", indexed: false, internalType: "string" },
      { name: "protocolFeeRate", type: "uint256", indexed: false, internalType: "uint256" },
    ],
  },
  {
    type: "event",
    name: "CreatorPoolActivated",
    inputs: [
      { name: "creator", type: "address", indexed: true, internalType: "address" },
    ],
  },
  {
    type: "event",
    name: "CreatorPoolDeactivated",
    inputs: [
      { name: "creator", type: "address", indexed: true, internalType: "address" },
    ],
  },
  {
    type: "event",
    name: "UserAdded",
    inputs: [
      { name: "creator", type: "address", indexed: true, internalType: "address" },
      { name: "user", type: "address", indexed: true, internalType: "address" },
      { name: "tokenAddress", type: "address", indexed: true, internalType: "address" },
      { name: "tokenType", type: "uint8", indexed: false, internalType: "enum ICreatorRewardPool.TokenType" },
      { name: "allocation", type: "uint256", indexed: false, internalType: "uint256" },
    ],
  },
  {
    type: "event",
    name: "AllocationUpdated",
    inputs: [
      { name: "creator", type: "address", indexed: true, internalType: "address" },
      { name: "user", type: "address", indexed: true, internalType: "address" },
      { name: "tokenAddress", type: "address", indexed: true, internalType: "address" },
      { name: "tokenType", type: "uint8", indexed: false, internalType: "enum ICreatorRewardPool.TokenType" },
      { name: "oldAllocation", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "newAllocation", type: "uint256", indexed: false, internalType: "uint256" },
    ],
  },
  {
    type: "event",
    name: "UserRemoved",
    inputs: [
      { name: "creator", type: "address", indexed: true, internalType: "address" },
      { name: "user", type: "address", indexed: true, internalType: "address" },
      { name: "tokenAddress", type: "address", indexed: true, internalType: "address" },
      { name: "tokenType", type: "uint8", indexed: false, internalType: "enum ICreatorRewardPool.TokenType" },
      { name: "allocation", type: "uint256", indexed: false, internalType: "uint256" },
    ],
  },
  {
    type: "event",
    name: "ProtocolFeeRecipientUpdated",
    inputs: [
      { name: "oldRecipient", type: "address", indexed: true, internalType: "address" },
      { name: "newRecipient", type: "address", indexed: true, internalType: "address" },
    ],
  },
  {
    type: "event",
    name: "DefaultProtocolFeeRateUpdated",
    inputs: [
      { name: "oldRate", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "newRate", type: "uint256", indexed: false, internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "CreatorRewardPoolFactory__OnlyCallableByAdmin",
    inputs: [],
  },
  {
    type: "error",
    name: "CreatorRewardPoolFactory__NoPoolForCreator",
    inputs: [],
  },
  {
    type: "error",
    name: "CreatorRewardPoolFactory__PoolAlreadyExists",
    inputs: [],
  },
  { type: "error", name: "CreatorRewardPoolFactory__ZeroAddress", inputs: [] },
  {
    type: "error",
    name: "CreatorRewardPoolFactory__PoolNotActive",
    inputs: [],
  },
  {
    type: "error",
    name: "CreatorRewardPoolFactory__InvalidCreator",
    inputs: [],
  },
  {
    type: "error",
    name: "CreatorRewardPoolFactory__InvalidProtocolFeeRate",
    inputs: [],
  },
  {
    type: "error",
    name: "AccessControlUnauthorizedAccount",
    inputs: [
      { name: "account", type: "address", internalType: "address" },
      { name: "neededRole", type: "bytes32", internalType: "bytes32" },
    ],
  },
  { type: "error", name: "AccessControlBadConfirmation", inputs: [] },
  { type: "error", name: "CreatorRewardPool__OnlyFactory", inputs: [] },
  { type: "error", name: "CreatorRewardPool__PoolNotActive", inputs: [] },
  { type: "error", name: "CreatorRewardPool__UserNotInPool", inputs: [] },
  { type: "error", name: "CreatorRewardPool__InvalidSignature", inputs: [] },
  { type: "error", name: "CreatorRewardPool__NonceAlreadyUsed", inputs: [] },
  { type: "error", name: "CreatorRewardPool__InvalidNonce", inputs: [] },
  { type: "error", name: "CreatorRewardPool__InsufficientRewards", inputs: [] },
  { type: "error", name: "CreatorRewardPool__ZeroAddress", inputs: [] },
  { type: "error", name: "CreatorRewardPool__ZeroAllocation", inputs: [] },
  { type: "error", name: "CreatorRewardPool__UserAlreadyExists", inputs: [] },
  { type: "error", name: "CreatorRewardPool__TransferFailed", inputs: [] },
  { type: "error", name: "CreatorRewardPool__InvalidTokenType", inputs: [] },
  {
    type: "error",
    name: "CreatorRewardPool__InvalidAllocationAmount",
    inputs: [],
  },
  { type: "error", name: "CreatorRewardPool__AlreadyClaimed", inputs: [] },
  {
    type: "error",
    name: "CreatorRewardPool__CannotUpdateAllocationsWhenActive",
    inputs: [],
  },
  {
    type: "error",
    name: "CreatorRewardPool__InsufficientPoolBalance",
    inputs: [],
  },
  {
    type: "error",
    name: "CreatorRewardPool__CannotWithdrawWhenActive",
    inputs: [],
  },
  {
    type: "error",
    name: "CreatorRewardPool__InvalidProtocolFeeRate",
    inputs: [],
  },
  {
    type: "error",
    name: "CreatorRewardPool__AllocationsExceedBalance",
    inputs: [],
  },
] as const;

export default creatorRewardPoolFactoryAbi;
