export const creatorRewardPoolAbi = [
  {
    type: "function",
    name: "SIGNER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_active",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_totalAllocations",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCreator",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProtocolFeeRate",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProtocolFeeRecipient",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDomainSeparator",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserAllocation",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isUser",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalUsers",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserAtIndex",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasClaimed",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalClaimed",
    inputs: [
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProtocolFeesClaimed",
    inputs: [
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAvailableRewards",
    inputs: [
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserNonceCounter",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isNonceUsed",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "nonce", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getNextNonce",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "validateAllocations",
    inputs: [
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
    ],
    outputs: [
      { name: "isValid", type: "bool", internalType: "bool" },
      { name: "totalAllocations", type: "uint256", internalType: "uint256" },
      { name: "availableBalance", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "checkClaimEligibility",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "tokenAddress", type: "address", internalType: "address" },
      {
        name: "tokenType",
        type: "uint8",
        internalType: "enum ICreatorRewardPool.TokenType",
      },
    ],
    outputs: [
      { name: "canClaim", type: "bool", internalType: "bool" },
      { name: "allocation", type: "uint256", internalType: "uint256" },
      { name: "protocolFee", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimReward",
    inputs: [
      {
        name: "data",
        type: "tuple",
        internalType: "struct ICreatorRewardPool.ClaimData",
        components: [
          { name: "user", type: "address", internalType: "address" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "tokenAddress", type: "address", internalType: "address" },
          {
            name: "tokenType",
            type: "uint8",
            internalType: "enum ICreatorRewardPool.TokenType",
          },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimRewardFor",
    inputs: [
      {
        name: "data",
        type: "tuple",
        internalType: "struct ICreatorRewardPool.ClaimData",
        components: [
          { name: "user", type: "address", internalType: "address" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "tokenAddress", type: "address", internalType: "address" },
          {
            name: "tokenType",
            type: "uint8",
            internalType: "enum ICreatorRewardPool.TokenType",
          },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "RewardClaimed",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "tokenAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "grossAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "netAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "protocolFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tokenType",
        type: "uint8",
        indexed: false,
        internalType: "enum ICreatorRewardPool.TokenType",
      },
      {
        name: "userAllocation",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalAllocations",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolFeeCollected",
    inputs: [
      {
        name: "tokenAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tokenType",
        type: "uint8",
        indexed: false,
        internalType: "enum ICreatorRewardPool.TokenType",
      },
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "event", name: "PoolActivated", inputs: [], anonymous: false },
  { type: "event", name: "PoolDeactivated", inputs: [], anonymous: false },
  {
    type: "event",
    name: "UserAdded",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "allocation",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UserAllocationUpdated",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "oldAllocation",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newAllocation",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UserRemoved",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "allocation",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "CreatorRewardPool__OnlyFactory", inputs: [] },
  { type: "error", name: "CreatorRewardPool__PoolNotActive", inputs: [] },
  { type: "error", name: "CreatorRewardPool__UserNotInPool", inputs: [] },
  { type: "error", name: "CreatorRewardPool__InvalidSignature", inputs: [] },
  { type: "error", name: "CreatorRewardPool__NonceAlreadyUsed", inputs: [] },
  { type: "error", name: "CreatorRewardPool__InvalidNonce", inputs: [] },
  { type: "error", name: "CreatorRewardPool__InsufficientRewards", inputs: [] },
  { type: "error", name: "CreatorRewardPool__ZeroAddress", inputs: [] },
  { type: "error", name: "CreatorRewardPool__ZeroAllocation", inputs: [] },
  { type: "error", name: "CreatorRewardPool__UserAlreadyExists", inputs: [] },
  { type: "error", name: "CreatorRewardPool__TransferFailed", inputs: [] },
  { type: "error", name: "CreatorRewardPool__InvalidTokenType", inputs: [] },
  {
    type: "error",
    name: "CreatorRewardPool__InvalidAllocationAmount",
    inputs: [],
  },
  { type: "error", name: "CreatorRewardPool__AlreadyClaimed", inputs: [] },
  {
    type: "error",
    name: "CreatorRewardPool__CannotUpdateAllocationsWhenActive",
    inputs: [],
  },
  {
    type: "error",
    name: "CreatorRewardPool__InsufficientPoolBalance",
    inputs: [],
  },
  {
    type: "error",
    name: "CreatorRewardPool__CannotWithdrawWhenActive",
    inputs: [],
  },
  {
    type: "error",
    name: "CreatorRewardPool__InvalidProtocolFeeRate",
    inputs: [],
  },
  {
    type: "error",
    name: "CreatorRewardPool__AllocationsExceedBalance",
    inputs: [],
  },
  {
    type: "error",
    name: "AccessControlUnauthorizedAccount",
    inputs: [
      { name: "account", type: "address" },
      { name: "neededRole", type: "bytes32" },
    ],
  },
  { type: "error", name: "AccessControlBadConfirmation", inputs: [] },
] as const;

export default creatorRewardPoolAbi;
